Develop
key0423/topiposu_namuru pull request #1
Opened 2021-01-20 15:24 UTC by key0423

・トップ作成
・お知らせモーダルのjQuery作成

2021-01-24 05:07 UTC, ShunMinase requested changes
現段階で気になる部分にコメントを付けさせていただきました。ご確認いただけたらうれしいです。

2021-01-24 05:07 UTC, ShunMinase commented on js/common.js
> +//トップへ戻るボタン
インデントの整理をお願いします。(このファイルに限らず)

2021-01-24 05:07 UTC, ShunMinase commented on mypage.html
> +<!DOCTYPE html>
インデントの整理をお願いします。(このファイルに限らず)

2021-01-24 05:07 UTC, ShunMinase commented on scss/foundation/_constants.scss
> +// メディアクエリー
constants.scssは変数(定数)を管理するためのファイルとして使いたいので、変数定義以外の記述は別ファイルへの切り出しをお願いしたいです。

2021-01-24 05:07 UTC, ShunMinase commented on scss/foundation/_object.scss
> +.bg_white{
"{"の前は1スペース空ける等、フォーマットについてコーディングガイドラインに沿った記述をお願いしたいです。(このファイルに限らず)
「SCSS Formatter」という拡張機能を導入いただくと楽かもです。導入するとalt+shift+fで自動フォーマットができます。

2021-01-24 05:07 UTC, ShunMinase commented on scss/foundation/_constants.scss
> +.post_link_txt_icon::before{
このファイルに限った話ではないのですが、ポストの英語名は「mailbox」に、おたよりの英語名は「message」に、それぞれ統一したいです。
「post」は「投稿」、「letter」は「文字」というように、ともに同音異義語があり紛らわしいためです。

2021-01-24 05:07 UTC, ShunMinase commented on mypage.html
> +<span class="fontawesome_icon post_link_txt_icon">最新のおたよりをのぞいてみる</span>
「最新のおたよりをのぞいてみる」の部分は不要になったため削除いただいて大丈夫です。(QA No.100参照)

2021-01-24 05:07 UTC, ShunMinase commented on mypage.html
> +<ul class="header_right flex">
ヘッダーに「よくある質問」へリンクするアイコンの配置をお願いします。(ヘルプマークみたいなやつ)

2021-01-24 05:07 UTC, ShunMinase commented on mypage.html
> +<header class="l_header flex_side">
ヘッダーの幅はコンテンツ幅と同じでよいと思われます。

2021-01-24 05:22 UTC, key0423 commented on scss/foundation/_object.scss
> +.bg_white{
インデント修正しました

2021-01-24 05:23 UTC, key0423 commented on js/common.js
> +//トップへ戻るボタン
インデント修正しました

2021-01-24 05:23 UTC, key0423 commented on mypage.html
> +<!DOCTYPE html>
インデント修正しました

2021-01-30 10:58 UTC, key0423 commented on scss/foundation/_constants.scss
> +// メディアクエリー
修正しました

2021-01-30 11:08 UTC, key0423 commented on scss/foundation/_constants.scss
> +.post_link_txt_icon::before{
修正しました

2021-01-30 12:20 UTC, key0423 commented on mypage.html
> +<ul class="header_right flex">
修正しました

2021-01-31 14:59 UTC, ShunMinase commented on scss/foundation/_fontawesome.scss
> +.cog_icon::before {
"cog"という単語からは意味を想像できないため、別の単語に変更お願いします。

2021-01-31 15:02 UTC, ShunMinase commented on scss/foundation/_constants.scss
> +@mixin link_btn_white($background:#fff,$font-color:#E6636C){
「$font-color」について
単語の区切りはアンダースコアで統一したいです。

2021-01-31 15:03 UTC, ShunMinase commented on scss/foundation/_constants.scss
> +$sp_min: 320px;
(ここに限らず)単語の区切りはアンダースコアで統一したいです。

2021-02-01 12:37 UTC, key0423 commented on mypage.html
> +<header class="l_header flex_side">
修正すなすた

2021-02-01 13:53 UTC, key0423 commented on mypage.html
> +<span class="fontawesome_icon post_link_txt_icon">最新のおたよりをのぞいてみる</span>
修正しました

2021-02-01 13:53 UTC, key0423 commented on mypage.html
> +<ul class="header_right flex">
修正しました

2021-02-01 13:53 UTC, key0423 commented on mypage.html
> +<header class="l_header flex_side">
修正しました

2021-03-12 14:48 UTC, key0423 commented on scss/foundation/_constants.scss
> +@mixin link_btn_white($background:#fff,$font-color:#E6636C){
修正しました

2021-03-12 14:48 UTC, key0423 commented on scss/foundation/_constants.scss
> +$sp_min: 320px;
修正しました

2021-03-12 15:37 UTC, key0423 commented on scss/foundation/_fontawesome.scss
> +.cog_icon::before {
修正しました！

2021-03-13 12:22 UTC, merged